DEVICE: 'cuda:0'
NUM_WORKERS: 4
SEED_NUM: 2

DATASET:
  name: 'DSECEvent'
  path: '/defaultShare/archive/pengchenxu/OminiXFusion/input/DSEC/DSEC_events/' # Replace with your own path
  require_paired_data: True
  classes: 11
  event_representation: 'voxel_grid'
  fixed_duration: False  
  delta_t: 50
  nr_events: 100000
  nr_bins: 10
  img_chnls: 3
  data_type: 'fusion'
  img_size: [440, 640]

MODEL:
  name: 'Evita_Pico'
  pretrained: "model_best_new.pth.tar"
  event_rep: 'None'
  fuse: 'exp001'

TRAIN:
  lr_scheduler: 'pcx'
  avg_top_k: 2
  warmup_iters: 500
  batch_size: 4
  lr_init: 0.00003
  num_epochs: 80
  save_every_n_epochs: 30
  log_dir: 'log/DDD17/test'

EVAL:
  batch_size: 6
  weight_path: "best_model_Evita_P_ddd17.pth"
